# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-16 17:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0002_paciente_activo'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='telefono',
            field=models.IntegerField(null=True, blank=True),
        ),
    ]
