# -*- coding: utf-8 -*-
from django import forms
from apps.historiaclinica.models import HistoriaClinica
from apps.paciente.models import Paciente


class HistoriaClinicaForm(forms.ModelForm):

    class Meta:
        model = HistoriaClinica
        fields = [
            'paciente',
            'tratamiento_medico',
            'medicamento_actual',
            'intervencion_quirurgica',
            'recibido_transfusion_sanguinea',
            'consume_droga',
            'consume_alcohol',
            'dolor_intenso_cabeza',
            'alergia_piel',
            'sangrado_excesivo',
            'penicilina',
            'anestesia',
            'aspirina',
            'merthiolate',
            'arterial_alta',
            'arterial_baja',
            'anemia',
            'diabetes',
            'problemas_corazon',
            'fiebre_reumatica',
            'epilepsia',
            'artritis',
            'hepatitis',
            'asma',
            'ulcera_gastrica',
            'tiroides',
            'leucemia',
            'hemofilia',
            'deficit',
            'vih',
            'retroviral',
            'embarazada',
            'dolor_intenso_cabeza',
            'pastillas_anticonceptivas',
            'limitacion_abrir_cerrar_boca',
            'ruido_abrir_cerrar_boca',
            'herper_aftas',
            'moder_unas',
            'consume_citricos', 
            'fuma',
            'muerde_objetos',
            'apretamiento_dentario',
            'respiracion_bucal',
            'sensibilidad_liquido_frio',
            'sensibilidad_liquido_caliente',
            'mismo_problema',
            'ultima_consulta',
            'ultima_radiografia',
            'obturacion',
            'endodoncia',
            'extraccion',
            'puente',
            'corona',
            'dentadura',
            'implante',
            'instruccion_higiene',
            'instruccion_evitar_carie',
            'instruccion_cuidar_encia',
            'diente_flojo',
            'diente_largo',
            'cepillado_dental',
        ]
        labels = {       
            'paciente': 'Nombre del Paciente:',
            'tratamiento_medico': '¿Está usted bajo tratamiento médico?:',
            'medicamento_actual': '¿Toma actualmente algún medicamento?:',
            'intervencion_quirurgica': '¿Le han practicado alguna intervención quirúrgica?:',
            'recibido_transfusion_sanguinea': '¿Ha recibido alguna transfusión sanguínea?:',
            'consume_droga': '¿Ha consummido o consume drogas?:',
            'consume_alcohol': '¿Toma bebidas alcohólicas?:',
            'dolor_intenso_cabeza': '¿Sufre con frecuencia dolores intensos de cabeza?:',
            'alergia_piel': '¿Tiene problemas alérgicos en la piel al usar pendientes, anillos, pulceras, etc.?:',
            'sangrado_excesivo': '¿Sangra excesivamente al cortarse?:',
            'penicilina': 'Penicilina:',
            'anestesia': 'Anestesia:',
            'aspirina': 'Aspirina, Yodo:',
            'merthiolate': 'Merthiolate:',
            'arterial_alta': 'Alta:',
            'arterial_baja': 'Baja:',
            'anemia': 'Anemia:',
            'diabetes': 'Diabetes:',
            'problemas_corazon': 'Problemas del corazón:',
            'fiebre_reumatica': 'Fiebre reumática:',
            'epilepsia': 'Epilepsia:',
            'artritis': 'Artritis:',
            'hepatitis': 'Hepatitis:',
            'asma': 'Asma:',
            'ulcera_gastrica': 'Ulcera gástrica:',
            'tiroides': 'Tiroides:',
            'leucemia': 'Leucemia:',
            'hemofilia': 'Hemofilia:',
            'deficit': 'Deficit Vit. K:',
            'vih': '¿Es usted V.I.H.+?:',
            'retroviral': '¿Toma algún medicamento retroviral?:',
            'embarazada': '¿Está usted embarazada?:',
            'pastillas_anticonceptivas': '¿Está tomando actualmente pastillas anticonceptivas?:',
            'limitacion_abrir_cerrar_boca': '¿Ha tenido limitación al abrir o cerrar la boca?:',
            'ruido_abrir_cerrar_boca': '¿Siente ruido en la mandibula al abrir o cerrar la boca?:',
            'herper_aftas': '¿Sufre de herper o aftas recurrentes?:',
            'moder_unas': '¿Morderse las uñas o labios?:',
            'consume_citricos': '¿Consume alimentos cítricos?:', 
            'fuma': '¿Fuma cigarrillos?:',
            'muerde_objetos': '¿Muerde objectos con los dientes?:',
            'apretamiento_dentario': 'Apretamiento dentario:',
            'respiracion_bucal': 'Respiración bucal:',
            'sensibilidad_liquido_frio': '¿Tiene sensibilidad con líquidos frios?:',
            'sensibilidad_liquido_caliente': '¿Tiene sensibilidad con líquidos calientes?:',
            'mismo_problema': '¿Lo tenía la última vez que fue al dentista?:',
            'ultima_consulta': '¿Cuánto tiempo hace que fue al dentista?:',
            'ultima_radiografia': '¿Cuándo y dondé se tomó la última radiografía de toda la boca?:',
            'obturacion': 'Obturación:',
            'endodoncia': 'Endodoncia:',
            'extraccion': 'Extracción:',
            'puente': 'Puente:',
            'corona': 'Coronas:',
            'dentadura': 'Dentadura:',
            'implante': 'Implante:',
            'instruccion_higiene': '¿Ha recibido instraucciones de higiene oral?:',
            'instruccion_evitar_carie': '¿Ha recibido instrucciones para evitar las caries?:',
            'instruccion_cuidar_encia': '¿Ha recibido instrucciones para cuidar sus encías?:',
            'diente_flojo': '¿Tiene dientes que se mueven?:',
            'diente_largo': '¿Ha notado sus dientes más largos?:',
            'cepillado_dental': '¿Se cepilla los dientes al diario?:',
        }
        widgets = {
           
            'paciente': forms.Select(choices=Paciente.objects.all().filter(activo=True).values_list('id',
                                    'nombre','apellido_paterno','apellido_materno'),
                                    attrs={'class': 'form-control'}),
            'ultima_consulta': forms.TextInput(attrs={'class': 'form-control'}),
            'ultima_radiografia': forms.TextInput(attrs={'class': 'form-control'}),
        }